//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallet.Collection.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wallet.Collection.Domain.Resource.ResponseMessage", typeof(ResponseMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction completed successfully..
        /// </summary>
        internal static string RM0000 {
            get {
                return ResourceManager.GetString("RM0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical problem. Please try again..
        /// </summary>
        internal static string RM0001 {
            get {
                return ResourceManager.GetString("RM0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical problem. Please try again..
        /// </summary>
        internal static string RM0002 {
            get {
                return ResourceManager.GetString("RM0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist..
        /// </summary>
        internal static string USR0001 {
            get {
                return ResourceManager.GetString("USR0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string USR0002 {
            get {
                return ResourceManager.GetString("USR0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string USR0003 {
            get {
                return ResourceManager.GetString("USR0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string USR0004 {
            get {
                return ResourceManager.GetString("USR0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string USR0005 {
            get {
                return ResourceManager.GetString("USR0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or password..
        /// </summary>
        internal static string USR0006 {
            get {
                return ResourceManager.GetString("USR0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password error..
        /// </summary>
        internal static string USR0007 {
            get {
                return ResourceManager.GetString("USR0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been blocked..
        /// </summary>
        internal static string USR0008 {
            get {
                return ResourceManager.GetString("USR0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is passive..
        /// </summary>
        internal static string USR0009 {
            get {
                return ResourceManager.GetString("USR0009", resourceCulture);
            }
        }
    }
}
